name: CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: extract 
        run: make extract 
      - name: transform_load
        run: make transform_load
      - name: query
        env: 
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
          HTTP_PATH: ${{ secrets.HTTP_PATH }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

        run: make query
      - name: test
        run: make test
      - name: format
        run: make format
      